config/routes.rb
Rails.application.routes.draw do
  # root "posts#index"

  root "splash#show"
  # root "articles#index"

  # JUST FOR TESTING.  DELETE WHEN FINISHED
  resources :posts, only: :index

  # post '/email_processor' is the SendGrid spec route
  # 'griddler/emails#create' triggers the Griddler gem from processing
  post '/email_processor' => 'griddler/emails#create'

  resources :users, except: :new do 
    resources :articles#, shallow: true
    resources :followers, except: [:edit, :update]
    resources :followees, except: [:edit, :update] do 
      get 'discover', on: :collection
    end
  end


  get "/sign_up" => "users#new", :as => "sign_up"
  
  get "/log_out" => "sessions#destroy", :as => "log_out"
  get "/log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: :create

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, through: :saved_articles
  has_many :saved_articles

  # source: :follower matches with the belong_to :follower identification in the Follow model 
  has_many :followers, through: :follower_follows, source: :follower
  # follower_follows "names" the Follow join table for accessing through the follower association
  has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow"

  # source: :followee matches with the belong_to :followee identification in the Follow model 	
  has_many :followees, through: :followee_follows, source: :followee
  # followee_follows "names" the Follow join table for accessing through the followee association
  has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"


  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password_salt
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.hashed_password == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.hashed_password = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def followers_with_user
    { user_id: self.id, followers: self.followers }
  end

  def followees_with_user
    { user_id: self.id, followees: self.followees }
  end

  def discoverable_users_with_user
    { user_id: self.id, discoverable_users: self.discoverable_users }    
  end


  def articles_with_user_and(current_user)
    { users: { user_id: self.id, current_user_id: current_user.id }, articles: self.articles }
  end

  def discoverable_users
    # TO DO: make more robust discoverable algorithm
    # self.class.where(id: self.id) turns self into [self]
    self.class.all - self.followees - self.class.where(id: self.id)
  end

  def a_follower?(followee)
    self.followees.include? followee
  end

  def update_articles
    new_user_posts = self.any_new_posts
    unless new_user_posts[0] == nil

      new_user_posts.each do |user_post|
        # match each Post's url with any previously created Article
        # we do this to avoid scraping the same web page more than once and creating duplicate Articles
        if user_post.an_article
          SavedArticle.save_article(self, user_post.an_article)
        else
          # Any new post (i.e. any url that hasn't already been scrapped and turning into an Article) is turned into an Article (through Pismo processing)
          # Then the Article is linked to the User through creation of a SavedArticle
          article = Article.create_article(user_post)
          SavedArticle.save_article(self, article) 
        end
      end
    end
  end

  # private

  def any_new_posts
    posts = Post.where(email: self.email).to_a
    # Deletes all of the user's posts that have already been turned into Articles and linked to the User (through a SavedArticle)
    # Note that if a User posts an article more than once (even months apart), such post will not be send to def update_articles, and no additioonal SavedArticle will be created
    # In other words, we may want to change the below to allow a user to email himself an article more than once
    # Then again, doing so would not filter out accidental diplicate emails/posts
    self.articles.each do |article|
      posts.delete_if { |post| ( article.post_id == post.id ) || ( article.a_url == post.a_url ) }
    end
    return posts
  end

  def serializable_hash(options = nil)
    {id: id, first_name: first_name, last_name: last_name, picture: picture}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_attributes)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_articles_path(@user.id), :notice => "Signed up!"
    else
      render "new"
    end
  end


  private

  def user_attributes
    params.require(:user).permit(:email, :password, :first_name, :last_name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
    <head>


    <div class="col-xs-4 col-xs-offset-4"><br>

      <%= form_for @user, :html => {:class => "form-signin", :role => "form"} do |f| %><br>
          <% if @user.errors.any? %>
            <div class="error_messages">
              <h2>Form is invalid</h2>
              <ul>
                <% for message in @user.errors.full_messages %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <h2 class="form-signin-heading">Please sign up</h2><br>
         <%= f.text_field :first_name, :class => 'form-control', :placeholder => "First Name" %><br>
          <%= f.text_field :last_name, :class => 'form-control', :placeholder => "Last Name"  %><br>
        <%= f.text_field :email, :class => 'form-control', :placeholder => "Email"  %><br>
        <%= f.password_field :password, :class => 'form-control', :placeholder => "Password" %><br>
        <%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => "Confirm Password"  %><br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
      <% end %>

    </div> <!-- /container -->

</head>


 

app/views/users/show.html.erb
<!-- Carousel
    ================================================== -->


    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators --><!--
      Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p> -->

      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class=""></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
      </ol>
      <div>
      <div class="carousel-inner">
        <div class="item">
          <img src="/assets/dead_leaves.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Read the content you want at the time you want.</h1>
              <p>Leaf lets you save.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/assets/barnyard.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Read the best content on your own time.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item active">
          <img src="/assets/leaf_backdrop.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Discover. Save. Read. Share.</h1>
              <h3>The internet is polluted with top ten lists and advertisements. Let LEAf help you discover real/substantiated content, build a refuge for the articles you want to read and create a sanctuary for the videos you want to see.</h3>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Try us out</a> <h3> <!-- | <%= link_to "Login", log_in_path %> <h3></p> -->
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>